# Generated by Django 4.0.5 on 2022-09-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='questions',
        ),
    ]
