version: '3'
services:

  backend:
    container_name: backend
    build: Backend
    restart: always
    volumes:
      - ./Backend:/app
    ports:
      - 8000:8000
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: frontend
    build: Frontend
    restart: always
    ports:
      - 4200:80
    depends_on:
      - backend