version: '3'
services:

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=skhan
      - POSTGRES_PASSWORD=haha
      - POSTGRES_DB=exam_hall

  backend:
    container_name: backend
    build: Backend
    restart: always
    ports:
      - 8000:8000
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: Frontend
    restart: always
    ports:
      - 4200:80
    depends_on:
      - backend