# Generated by Django 4.1.1 on 2023-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturemodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
