# Generated by Django 4.1.1 on 2023-05-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_alter_classmodel_table_alter_lecturemodel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassModel',
            new_name='CourseModel',
        ),
        migrations.RenameField(
            model_name='lecturemodel',
            old_name='class_info',
            new_name='course',
        ),
    ]
