# Generated by Django 4.1.1 on 2022-12-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('examId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('numberForCorrectAnswer', models.IntegerField(default=0)),
                ('numberForIncorrectAnswer', models.IntegerField(default=0)),
                ('numberOfSeats', models.IntegerField(default=0)),
                ('questions', models.ManyToManyField(related_name='exams', to='question.questionmodel')),
                ('topics', models.ManyToManyField(related_name='exams', to='topic.topicmodel')),
            ],
        ),
    ]
