# Generated by Django 4.2.11 on 2024-10-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examparticipantmodel',
            name='answer_sheet',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='examparticipantmodel',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
