# Generated by Django 4.1.1 on 2023-04-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exammodel',
            old_name='examId',
            new_name='exam_id',
        ),
        migrations.RenameField(
            model_name='exammodel',
            old_name='numberForCorrectAnswer',
            new_name='number_for_correct_answer',
        ),
        migrations.RenameField(
            model_name='exammodel',
            old_name='numberForIncorrectAnswer',
            new_name='number_for_incorrect_answer',
        ),
        migrations.RenameField(
            model_name='exammodel',
            old_name='numberOfSeats',
            new_name='number_of_seats',
        ),
    ]
