# Generated by Django 4.1.1 on 2023-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examparticipantmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examparticipantmodel',
            name='exam_end_time',
            field=models.DateTimeField(default=None),
        ),
    ]
