# Generated by Django 3.2.15 on 2023-04-10 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_examid_exammodel_exam_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='number_for_incorrect_answer',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(0.0)]),
        ),
    ]
