# Generated by Django 4.2.11 on 2024-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examparticipantmodel_answer_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examparticipantmodel',
            name='answer_sheet',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
