# Generated by Django 4.1.1 on 2023-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_examparticipantmodel_exam_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examparticipantmodel',
            name='exam_end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
