# Generated by Django 3.2.15 on 2023-04-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exammodel_number_for_incorrect_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='number_for_incorrect_answer',
            field=models.FloatField(default=0),
        ),
    ]
