# Generated by Django 4.1.1 on 2023-05-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_examparticipantmodel_exam_end_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exammodel',
            table='exams',
        ),
        migrations.AlterModelTable(
            name='examparticipantmodel',
            table='exam_participants',
        ),
    ]
