# Generated by Django 4.1.1 on 2023-05-14 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_alter_questionmodel_table_alter_topicmodel_table'),
        ('exam', '0005_alter_exammodel_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_correct_answer', models.FloatField(default=0)),
                ('number_of_incorrect_answer', models.FloatField(default=0)),
                ('marks', models.FloatField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exammodel')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.topicmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
