# Generated by Django 4.1.1 on 2023-05-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_resultmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultmodel',
            old_name='topic',
            new_name='subject',
        ),
    ]
