# Generated by Django 4.0.5 on 2022-06-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_questionmodel_option2_and_more'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='numberOfSeats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='questions',
            field=models.ManyToManyField(related_name='exams', to='question.questionmodel'),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='numberForCorrectAnswer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='numberForIncorrectAnswer',
            field=models.IntegerField(default=0),
        ),
    ]
