# Generated by Django 4.0.5 on 2022-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('service', '0002_exammodel_numberofseats_exammodel_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='topics',
            field=models.ManyToManyField(related_name='exams', to='topic.topicmodel'),
        ),
    ]
