# Generated by Django 4.1.1 on 2023-05-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='users',
        ),
    ]
