# Generated by Django 4.0.5 on 2022-06-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='questionText',
            new_name='qText',
        ),
    ]
