# Generated by Django 4.0.5 on 2022-06-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_questiontext_questionmodel_qtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='qText',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='questionText',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='answer',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='explaination',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='option1',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='option2',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='option3',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='option4',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='option5',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='option6',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
