# Generated by Django 4.0.5 on 2022-06-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='option1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
