# Generated by Django 4.1.1 on 2023-04-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='topicId',
            new_name='topic_id',
        ),
    ]
