# Generated by Django 4.0.5 on 2022-06-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_questionmodel_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
