# Generated by Django 4.0.5 on 2022-06-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_usermodel_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
