# Generated by Django 4.1.1 on 2023-04-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='questionId',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='questionText',
            new_name='question_text',
        ),
    ]
