# Generated by Django 4.1.1 on 2023-07-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionBankModel',
            new_name='ReferenceExam',
        ),
    ]
