# Generated by Django 4.1.1 on 2023-05-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionmodel',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='topicmodel',
            table='topics',
        ),
    ]
