# Generated by Django 4.1.1 on 2023-05-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_rename_topic_resultmodel_subject'),
        ('question', '0002_alter_questionmodel_table_alter_topicmodel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicModel',
            new_name='SubjectModel',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='topic',
            new_name='subject',
        ),
    ]
