# Generated by Django 4.1.1 on 2023-04-15 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_rename_questionid_questionmodel_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='archived_by_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
