# Generated by Django 4.1.1 on 2023-06-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_questionmodel_subject_chaptermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptermodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chapters', to='question.subjectmodel'),
        ),
    ]
