# Generated by Django 4.1.1 on 2023-06-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_chaptermodel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbankmodel',
            name='category',
            field=models.CharField(choices=[('BCS', 'BCS'), ('PRIMARY_SCHOOL', 'PRIMARY_SCHOOL')], max_length=50),
        ),
    ]
