# Generated by Django 4.1.1 on 2023-05-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_rename_topicmodel_subjectmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subjectmodel',
            table='subjects',
        ),
    ]
