# Generated by Django 4.1.1 on 2023-05-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_subjectmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'question_banks',
            },
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='question.questionbankmodel'),
        ),
    ]
