# Generated by Django 4.1.1 on 2023-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_questionbankmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbankmodel',
            name='exam_name',
            field=models.CharField(max_length=200),
        ),
    ]
