# Generated by Django 4.1.1 on 2023-04-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_rename_userarchivedquestionmodel_archivedquestionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedQuestionModel',
        ),
    ]
